### PR TITLE
Web crawling 2nd PR

### PR DESCRIPTION
**Pull request by JWWJGit**
# 👉Summary

### Added function to obtain news from Investopedia.

# 👀Detail

### Output: a list containing the latest ten news about the ticker
Screenshot 2023-07-13 at 1 14 47 AM

### CODE REVIEW

**Comment by YLee2121** [comment]
Could you add the screenshot or give an example input and the corresponding output?

**Comment by JWWJGit** [comment]
No problem, added.

**Review by YLee2121 — APPROVED** [review]
approve

**Review by alex308248 — APPROVED** [review]
Approved!

**Pull request merged**
